## Assignment 06
### Note:
- For visualization, you should use Plotly Express 
- Use this notebook as your template and follow the instructions

The first half of this assignment is similar to assignment 04.

This gives you a chance to refresh.

The second half is new and gives you a chance to perform additional practices.

You also get a chance to use some of the Python libraries and techniques.

The links to the zip file is:

- https://collegescorecard.ed.gov/data (This web page contains the link to the zip file)

- https://ed-public-download.app.cloud.gov/downloads/CollegeScorecard_Raw_Data_09012022.zip (The link to the zip file)

You can run `!wget` command in Colab notebook to retrieve it directly, then run `!unzip` command to extract files (I have provided the cells to do so next for your convenience)

Your folder structure should look like this in your Colab enviroment:

- ...
- 'MERGED1996_97_PP.csv',
- 'MERGED2015_16_PP.csv',
- ...
- 'MERGED2017_18_PP.csv'
- ...

**Note: you should refresh the folder to see all files.**

## Step 1 - Retrieve the zip file

In [1]:
!wget https://ed-public-download.app.cloud.gov/downloads/CollegeScorecard_Raw_Data_09012022.zip

--2022-10-09 19:53:44--  https://ed-public-download.app.cloud.gov/downloads/CollegeScorecard_Raw_Data_09012022.zip
Resolving ed-public-download.app.cloud.gov (ed-public-download.app.cloud.gov)... 3.30.138.208, 3.30.49.38, 2600:1f12:18a:7d00:35c5:2f94:bca6:6240, ...
Connecting to ed-public-download.app.cloud.gov (ed-public-download.app.cloud.gov)|3.30.138.208|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 410294884 (391M) [application/zip]
Saving to: ‘CollegeScorecard_Raw_Data_09012022.zip’

CollegeScorecard_Ra 100%[===================>] 391.29M  68.0MB/s    in 6.1s

2022-10-09 19:53:50 (64.1 MB/s) - ‘CollegeScorecard_Raw_Data_09012022.zip’ saved [410294884/410294884]

## Step 2 - Unzip the zip file

In [2]:
!unzip CollegeScorecard_Raw_Data_09012022.zip

Archive:  CollegeScorecard_Raw_Data_09012022.zip
 extracting: Crosswalks.zip
  inflating: data.yaml
  inflating: FieldOfStudyData1415_1516_PP.csv
  inflating: FieldOfStudyData1516_1617_PP.csv
  inflating: FieldOfStudyData1617_1718_PP.csv
  inflating: FieldOfStudyData1718_1819_PP.csv
  inflating: MERGED1996_97_PP.csv
  inflating: MERGED1997_98_PP.csv
  inflating: MERGED1998_99_PP.csv
  inflating: MERGED1999_00_PP.csv
  inflating: MERGED2000_01_PP.csv
  inflating: MERGED2001_02_PP.csv
  inflating: MERGED2002_03_PP.csv
  inflating: MERGED2003_04_PP.csv
  inflating: MERGED2004_05_PP.csv
  inflating: MERGED2005_06_PP.csv
  inflating: MERGED2006_07_PP.csv
  inflating: MERGED2007_08_PP.csv
  inflating: MERGED2008_09_PP.csv
  inflating: MERGED2009_10_PP.csv
  inflating: MERGED2010_11_PP.csv
  inflating: MERGED2011_12_PP.csv
  inflating: MERGED2012_13_PP.csv
  inflating: MERGED2013_14_PP.csv
  inflating: MERGED2014_15_PP.csv
  inflating: MERGED2015_16_PP.csv
  inflating: MERGED2016_17_PP.csv
  inflating: MERGED2017_18_PP.csv
  inflating: MERGED2018_19_PP.csv
  inflating: MERGED2019_20_PP.csv
  inflating: MERGED2020_21_PP.csv
  inflating: Most-Recent-Cohorts-Field-of-Study.csv
  inflating: Most-Recent-Cohorts-Institution.csv

## Step 3 - Import Libraries

In [3]:
#(Write code below)

# Importing library for creating directory or folder
import os

## Step 4 - Display the current working directory using os.getcwd()

You would need to import a standard Python library called os which stands for operating system. so place that import statement in the previous cell. Since your notebook and your data files may or may not in the same folder, you want to make sure what the current working folder is and how to access a data file in a different folder.

In [4]:
#(Write code below)

# Returning the path of current working directory 
path_data = os.getcwd()

## Step 5 - Get the list of file names

os library has a method call listdir which generates a list of files in a directory/folder. Use this method to assign the contents (list of file names) of the data folder to a variable and display it. If necessary, you can use ../ construct to traverse to the parent folder and then to another foloder parallel to the current folder

In [5]:
#(Write code below)
list_dir = os.listdir(path_data)
print(list_dir)

['.config', 'MERGED2006_07_PP.csv', 'MERGED2009_10_PP.csv', 'MERGED2003_04_PP.csv', 'MERGED1998_99_PP.csv', 'Crosswalks.zip', 'MERGED2012_13_PP.csv', 'MERGED2019_20_PP.csv', 'MERGED2011_12_PP.csv', 'MERGED2014_15_PP.csv', 'Most-Recent-Cohorts-Field-of-Study.csv', 'MERGED2000_01_PP.csv', 'MERGED2007_08_PP.csv', 'MERGED2016_17_PP.csv', 'FieldOfStudyData1718_1819_PP.csv', 'MERGED2018_19_PP.csv', 'MERGED2008_09_PP.csv', 'MERGED2002_03_PP.csv', 'MERGED2004_05_PP.csv', 'MERGED2010_11_PP.csv', 'MERGED2013_14_PP.csv', 'MERGED2005_06_PP.csv', 'FieldOfStudyData1516_1617_PP.csv', 'MERGED1999_00_PP.csv', 'MERGED2015_16_PP.csv', 'MERGED1996_97_PP.csv', 'FieldOfStudyData1415_1516_PP.csv', 'FieldOfStudyData1617_1718_PP.csv', 'MERGED2017_18_PP.csv', 'data.yaml', 'Most-Recent-Cohorts-Institution.csv', 'MERGED1997_98_PP.csv', 'MERGED2020_21_PP.csv', 'CollegeScorecard_Raw_Data_09012022.zip', 'MERGED2001_02_PP.csv', 'sample_data']

## Step 6 - Process only the yearly data files

The folder contains files that are not the yearly data files. Write code to remove the unwanted files from the list variable.

Note: don't remove/delete these files from the folder in the folder.
For example, use the file extension to only use the csv files or use the name patter - data file name begins with "MERGED". You can use the concept of list comprehension to write just *one* line of code as well as using a for loop, your choice.

In [6]:
#(Write code below)

# Taking only the MERGED name files from the list of files
file_new = []
for flenme in list_dir:
    if flenme.startswith('MERGED'):
      file_new.append(flenme)
display(file_new)

['MERGED2006_07_PP.csv',
 'MERGED2009_10_PP.csv',
 'MERGED2003_04_PP.csv',
 'MERGED1998_99_PP.csv',
 'MERGED2012_13_PP.csv',
 'MERGED2019_20_PP.csv',
 'MERGED2011_12_PP.csv',
 'MERGED2014_15_PP.csv',
 'MERGED2000_01_PP.csv',
 'MERGED2007_08_PP.csv',
 'MERGED2016_17_PP.csv',
 'MERGED2018_19_PP.csv',
 'MERGED2008_09_PP.csv',
 'MERGED2002_03_PP.csv',
 'MERGED2004_05_PP.csv',
 'MERGED2010_11_PP.csv',
 'MERGED2013_14_PP.csv',
 'MERGED2005_06_PP.csv',
 'MERGED1999_00_PP.csv',
 'MERGED2015_16_PP.csv',
 'MERGED1996_97_PP.csv',
 'MERGED2017_18_PP.csv',
 'MERGED1997_98_PP.csv',
 'MERGED2020_21_PP.csv',
 'MERGED2001_02_PP.csv']

## Step 7 - Load data files
 
Now that you have a clean list of the yearly files, you want to loop through them and read them into a dataframe one at a time. You only load six columns: ["UNITID", "INSTNM", "STABBR", "REGION", "ADM_RATE", "TUITIONFEE_IN"].

You should use "usecols" option of Pandas to avoid reading unwanted columns. You also want to add a new column call "YEAR" to differentiate the data frames from each other. The YEAR variable should be yyyy format so tht you can convert them into integer. If you use the format yyyy-yy (such as 1997-98 school year), you will not be able to convert them directly to integer. If you use scatter plot, the YEAR needs to be converted to integer or float. 

You would use an empty list and append the yearly dataframes to the list. After all data files are loaded and appended to the list, you would use Pandas to concatenate them into a new single data frame.

Note: this exercise incorporates many techques we learned before:

- list (creating an empty, append an item to the list)
- for loop 
- read only the needed columns from a file (using usecols option)
- add a new column to a data frame
- concatenate multiple dataframes into a single one

This exercise may appear challenging but it worths the effort. You will learn a lot and love it. I promise.

In [7]:
#(Write code here)

from google.colab import files
import pandas as pd
lr =[]

for fw in file_new:
    d_w = pd.read_csv(fw, usecols = ["UNITID", "INSTNM", "STABBR", "REGION", "ADM_RATE", "TUITIONFEE_IN"])
    yearData=fw[6:10]
    dg = pd.to_datetime(yearData)
    d_w["YEAR"] = dg.year
    lr.append(d_w)

    d_w = pd.concat(lr)

d_w

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,YEAR
0,100636,Community College of the Air Force,AL,0.0,NaN,NaN,2006
1,100654,Alabama A & M University,AL,5.0,0.4118,3640.0,2006
2,100663,University of Alabama at Birmingham,AL,5.0,0.8778,4792.0,2006
3,100690,Amridge University,AL,5.0,NaN,6000.0,2006
4,100706,University of Alabama in Huntsville,AL,5.0,0.8834,4848.0,2006
...,...,...,...,...,...,...,...
6720,440855,Milan Institute-Amarillo,TX,6.0,1.0000,NaN,2001
6721,440864,Trinity College,CA,8.0,1.0000,NaN,2001
6722,440873,Vatterott College-Dividend,TN,5.0,0.9091,7520.0,2001
6723,440882,Vatterott College-Tulsa,OK,6.0,0.9106,6715.0,2001
6724,440891,Vatterott College-Wichita,KS,4.0,0.8654,8380.0,2001

## Step 8 - Explore the new dataframe 

For example, # of observations, varibles, head, tail, sample, missing values, statistics, etc.

In [8]:
#(Write code here)
d_w.dtypes

UNITID             int64
INSTNM            object
STABBR            object
REGION           float64
ADM_RATE         float64
TUITIONFEE_IN    float64
YEAR               int64
dtype: object

In [9]:
d_w.describe

<bound method NDFrame.describe of       UNITID                               INSTNM STABBR  REGION  ADM_RATE  \
0     100636   Community College of the Air Force     AL     0.0       NaN
1     100654             Alabama A & M University     AL     5.0    0.4118
2     100663  University of Alabama at Birmingham     AL     5.0    0.8778
3     100690                   Amridge University     AL     5.0       NaN
4     100706  University of Alabama in Huntsville     AL     5.0    0.8834
...      ...                                  ...    ...     ...       ...
6720  440855             Milan Institute-Amarillo     TX     6.0    1.0000
6721  440864                      Trinity College     CA     8.0    1.0000
6722  440873           Vatterott College-Dividend     TN     5.0    0.9091
6723  440882              Vatterott College-Tulsa     OK     6.0    0.9106
6724  440891            Vatterott College-Wichita     KS     4.0    0.8654

      TUITIONFEE_IN  YEAR
0               NaN  2006
1            3640.0  2006
2            4792.0  2006
3            6000.0  2006
4            4848.0  2006
...             ...   ...
6720            NaN  2001
6721            NaN  2001
6722         7520.0  2001
6723         6715.0  2001
6724         8380.0  2001

[176707 rows x 7 columns]>

In [10]:
d_w.head(10)

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,YEAR
0,100636,Community College of the Air Force,AL,0.0,NaN,NaN,2006
1,100654,Alabama A & M University,AL,5.0,0.4118,3640.0,2006
2,100663,University of Alabama at Birmingham,AL,5.0,0.8778,4792.0,2006
3,100690,Amridge University,AL,5.0,NaN,6000.0,2006
4,100706,University of Alabama in Huntsville,AL,5.0,0.8834,4848.0,2006
5,100724,Alabama State University,AL,5.0,0.6698,4008.0,2006
6,100751,The University of Alabama,AL,5.0,0.7004,5278.0,2006
7,100760,Central Alabama Community College,AL,5.0,NaN,2340.0,2006
8,100812,Athens State University,AL,5.0,NaN,NaN,2006
9,100830,Auburn University at Montgomery,AL,5.0,0.9801,4760.0,2006

In [11]:
d_w.tail(10)

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,YEAR
6715,440785,NEW ENGLAND CULINARY INST-H L STOUTT COMM COLL,VI,9.0,1.0000,9940.0,2001
6716,440800,Miami Ad School-Minneapolis,MN,4.0,NaN,NaN,2001
6717,440819,Miami Ad School-San Francisco,CA,8.0,NaN,NaN,2001
6718,440837,Winner Institute of Arts & Sciences,PA,2.0,NaN,12305.0,2001
6719,440846,Milan Institute-Boise,ID,7.0,1.0000,NaN,2001
6720,440855,Milan Institute-Amarillo,TX,6.0,1.0000,NaN,2001
6721,440864,Trinity College,CA,8.0,1.0000,NaN,2001
6722,440873,Vatterott College-Dividend,TN,5.0,0.9091,7520.0,2001
6723,440882,Vatterott College-Tulsa,OK,6.0,0.9106,6715.0,2001
6724,440891,Vatterott College-Wichita,KS,4.0,0.8654,8380.0,2001

In [12]:
d_w.sample(4)

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,YEAR
4384,438179,Brookline College-Tucson,AZ,6.0,NaN,NaN,2020
3558,213507,Lebanon Valley College,PA,2.0,0.7252,29350.0,2008
5870,490805,Purdue University Northwest,IN,3.0,0.3028,7942.0,2020
1022,140997,South Georgia College,GA,5.0,NaN,2154.0,2007

In [13]:
d_w.isna().any()

UNITID           False
INSTNM           False
STABBR           False
REGION            True
ADM_RATE          True
TUITIONFEE_IN     True
YEAR             False
dtype: bool

In [14]:
d_w.describe()

             UNITID         REGION      ADM_RATE  TUITIONFEE_IN           YEAR
count  1.767070e+05  176706.000000  48863.000000   86867.000000  176707.000000
mean   1.054338e+06       4.559279      0.693785   12037.588290    2008.176750
std    4.959072e+06       2.188341      0.217019   10462.970227       7.133143
min    1.006360e+05       0.000000      0.000000       0.000000    1996.000000
25%    1.641730e+05       3.000000      0.556700    3936.000000    2002.000000
50%    2.136310e+05       5.000000      0.719500    9422.000000    2008.000000
75%    4.137780e+05       6.000000      0.857100   16490.000000    2014.000000
max    4.957672e+07       9.000000      1.000000   74787.000000    2020.000000

In [15]:
d_w['TUITIONFEE_IN'].sum()

1045669182.0

In [16]:
d_w['TUITIONFEE_IN'].max()

74787.0

In [17]:
d_w['TUITIONFEE_IN'].count()

86867

In [18]:
d_w['TUITIONFEE_IN'].mean()

12037.588290144704

In [19]:
d_w['TUITIONFEE_IN'].median()

9422.0

## Step 9 - UMBC 

The dataframe contains many years of data of all U.S. colleges. let's just look at UMBC. Filter/query the dataframe to retrieve only rows that belong to UMBC (one row represent one year). Save the UMNC data to a new data frame. using a new variable for the UMBC data frame, so that the old big data frame is still available for later use.

In [20]:
#(Write code here)
d_um = d_w[d_w['INSTNM'] == 'University of Maryland-Baltimore County']
d_um

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,YEAR
1799,163268,University of Maryland-Baltimore County,MD,2.0,0.7153,8622.0,2006
1745,163268,University of Maryland-Baltimore County,MD,2.0,0.6890,8872.0,2009
1873,163268,University of Maryland-Baltimore County,MD,2.0,0.5757,7388.0,2003
1982,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1998
1660,163268,University of Maryland-Baltimore County,MD,2.0,0.6035,9764.0,2012
1391,163268,University of Maryland-Baltimore County,MD,2.0,0.6103,12028.0,2019
1694,163268,University of Maryland-Baltimore County,MD,2.0,0.6081,9467.0,2011
1610,163268,University of Maryland-Baltimore County,MD,2.0,0.5961,10384.0,2014
1926,163268,University of Maryland-Baltimore County,MD,2.0,NaN,5490.0,2000
1779,163268,University of Maryland-Baltimore County,MD,2.0,0.6895,8708.0,2007
1510,163268,University of Maryland-Baltimore County,MD,2.0,0.5683,11264.0,2016
1415,163268,University of Maryland-Baltimore County,MD,2.0,0.5794,11778.0,2018
1767,163268,University of Maryland-Baltimore County,MD,2.0,0.7174,8780.0,2008
1893,163268,University of Maryland-Baltimore County,MD,2.0,0.6327,6362.0,2002
1830,163268,University of Maryland-Baltimore County,MD,2.0,0.7014,8020.0,2004
1710,163268,University of Maryland-Baltimore County,MD,2.0,0.6589,9171.0,2010
1629,163268,University of Maryland-Baltimore County,MD,2.0,0.6315,10068.0,2013
1819,163268,University of Maryland-Baltimore County,MD,2.0,0.7143,8520.0,2005
1955,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1999
1555,163268,University of Maryland-Baltimore County,MD,2.0,0.5942,11006.0,2015
2151,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1996
1478,163268,University of Maryland-Baltimore County,MD,2.0,0.6021,11518.0,2017
2049,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1997
1375,163268,University of Maryland-Baltimore County,MD,2.0,0.6948,9420.0,2020
1915,163268,University of Maryland-Baltimore County,MD,2.0,0.6551,5910.0,2001

## Step 10 - Explore the new dataframe

For example, # of observations, varibles, head, tail, sample, missing values, statistics, etc

In [21]:
d_um

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,YEAR
1799,163268,University of Maryland-Baltimore County,MD,2.0,0.7153,8622.0,2006
1745,163268,University of Maryland-Baltimore County,MD,2.0,0.6890,8872.0,2009
1873,163268,University of Maryland-Baltimore County,MD,2.0,0.5757,7388.0,2003
1982,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1998
1660,163268,University of Maryland-Baltimore County,MD,2.0,0.6035,9764.0,2012
1391,163268,University of Maryland-Baltimore County,MD,2.0,0.6103,12028.0,2019
1694,163268,University of Maryland-Baltimore County,MD,2.0,0.6081,9467.0,2011
1610,163268,University of Maryland-Baltimore County,MD,2.0,0.5961,10384.0,2014
1926,163268,University of Maryland-Baltimore County,MD,2.0,NaN,5490.0,2000
1779,163268,University of Maryland-Baltimore County,MD,2.0,0.6895,8708.0,2007
1510,163268,University of Maryland-Baltimore County,MD,2.0,0.5683,11264.0,2016
1415,163268,University of Maryland-Baltimore County,MD,2.0,0.5794,11778.0,2018
1767,163268,University of Maryland-Baltimore County,MD,2.0,0.7174,8780.0,2008
1893,163268,University of Maryland-Baltimore County,MD,2.0,0.6327,6362.0,2002
1830,163268,University of Maryland-Baltimore County,MD,2.0,0.7014,8020.0,2004
1710,163268,University of Maryland-Baltimore County,MD,2.0,0.6589,9171.0,2010
1629,163268,University of Maryland-Baltimore County,MD,2.0,0.6315,10068.0,2013
1819,163268,University of Maryland-Baltimore County,MD,2.0,0.7143,8520.0,2005
1955,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1999
1555,163268,University of Maryland-Baltimore County,MD,2.0,0.5942,11006.0,2015
2151,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1996
1478,163268,University of Maryland-Baltimore County,MD,2.0,0.6021,11518.0,2017
2049,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1997
1375,163268,University of Maryland-Baltimore County,MD,2.0,0.6948,9420.0,2020
1915,163268,University of Maryland-Baltimore County,MD,2.0,0.6551,5910.0,2001

In [22]:
#(Write code here)
d_um.dtypes

UNITID             int64
INSTNM            object
STABBR            object
REGION           float64
ADM_RATE         float64
TUITIONFEE_IN    float64
YEAR               int64
dtype: object

In [23]:
d_um.head(3)

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,YEAR
1799,163268,University of Maryland-Baltimore County,MD,2.0,0.7153,8622.0,2006
1745,163268,University of Maryland-Baltimore County,MD,2.0,0.6890,8872.0,2009
1873,163268,University of Maryland-Baltimore County,MD,2.0,0.5757,7388.0,2003

In [24]:
d_um.tail(2)

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,YEAR
1375,163268,University of Maryland-Baltimore County,MD,2.0,0.6948,9420.0,2020
1915,163268,University of Maryland-Baltimore County,MD,2.0,0.6551,5910.0,2001

In [25]:
d_um.sample(2)

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,YEAR
1660,163268,University of Maryland-Baltimore County,MD,2.0,0.6035,9764.0,2012
1982,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1998

In [26]:
d_um.isna().any()

UNITID           False
INSTNM           False
STABBR           False
REGION           False
ADM_RATE          True
TUITIONFEE_IN     True
YEAR             False
dtype: bool

In [27]:
d_um.describe()

         UNITID  REGION   ADM_RATE  TUITIONFEE_IN         YEAR
count      25.0    25.0  20.000000      21.000000    25.000000
mean   163268.0     2.0   0.641880    9168.571429  2008.000000
std         0.0     0.0   0.051853    1854.082079     7.359801
min    163268.0     2.0   0.568300    5490.000000  1996.000000
25%    163268.0     2.0   0.600600    8520.000000  2002.000000
50%    163268.0     2.0   0.632100    9171.000000  2008.000000
75%    163268.0     2.0   0.690825   10384.000000  2014.000000
max    163268.0     2.0   0.717400   12028.000000  2020.000000

In [28]:
d_um['ADM_RATE'].sum()

12.837600000000002

In [29]:
d_um['ADM_RATE'].max()

0.7174

In [30]:
d_um['ADM_RATE'].min()

0.5683

In [31]:
d_um['ADM_RATE'].count()

20

In [32]:
d_um['ADM_RATE'].mean()

0.6418800000000001

In [33]:
d_um['ADM_RATE'].median()

0.6321

## Step 11 - Plot UMBC's in-state tution overtime Bar Chart

In [34]:
#(Write code here)
#  Sorting the Year column 

d_um = d_um.sort_values('YEAR', ascending=True)

In [87]:
# Importing Plotting libraries in-order to depict plots

import plotly.express as px


# Creating Bar plot

fig = px.bar(d_um, x = 'YEAR', y = 'TUITIONFEE_IN', color='YEAR')
fig.update_layout(title="UMBC in-state tution over time", hovermode="x")
fig.show()

## Step 12 - Plot UMBC's in-state tution overtime using line Chart

In [88]:
#(Write code here)

# Creating Line Plot

fig = px.line(d_um, x = 'YEAR', y = 'TUITIONFEE_IN')
fig.update_layout(title="UMBC in-state tution over time", hovermode="x")
fig.show()

## Step 13 - Tuition Growth Rate

Now let's look at the tuition growth rate year over year. We need to calculate UMBC tuition change percentage each year. First convert the TUITIONFEE_IN column to a Python List

In [37]:
#(Write code here)
# Filling the Missing values with '0' in Tuition fee column
d_um['TUITIONFEE_IN'] = d_um['TUITIONFEE_IN'].fillna(0)

In [38]:
# Converting the TUITIONFEE_IN column to a Python List

list_c = d_um['TUITIONFEE_IN'].to_list()
list_c

[0.0,
 0.0,
 0.0,
 0.0,
 5490.0,
 5910.0,
 6362.0,
 7388.0,
 8020.0,
 8520.0,
 8622.0,
 8708.0,
 8780.0,
 8872.0,
 9171.0,
 9467.0,
 9764.0,
 10068.0,
 10384.0,
 11006.0,
 11264.0,
 11518.0,
 11778.0,
 12028.0,
 9420.0]

## Step 14 - Loop through the list and calculate the % change each year over the prior year

This takes some effort. Not hard, just some abstract/logical thinking and some experiments. Have fun on this one.

In [39]:
 #(Write code here)

kl=[]
j=0
for i in range(0,len(list_c)):
  j=i+1
  if list_c[i]==0: # Conditional statement to avoid mathematical error (When any value is divided by 0, it won't work)
    pc=0
  else: 
    if j<len(list_c): 
      pc = ((list_c[j] - list_c[i])/list_c[i]) *100 # applying % change formula
    else:
      pc= 0  
  kl.append(pc)

In [40]:
kl

[0,
 0,
 0,
 0,
 7.650273224043716,
 7.648054145516074,
 16.12700408676517,
 8.554412560909583,
 6.234413965087282,
 1.1971830985915493,
 0.9974483878450475,
 0.8268259072117593,
 1.0478359908883828,
 3.370153291253381,
 3.227565151019518,
 3.1372134783986483,
 3.11347808275297,
 3.1386571315057608,
 5.989984591679507,
 2.344175904052335,
 2.254971590909091,
 2.2573363431151243,
 2.122601460349805,
 -21.68274027269704,
 0]

## Step 15 - Round up the percentage to two decimal points

The resulting number has many decimal points which are unnecessary and not visually appealing. You can use for loop. Or better, use list comprehension for simplicity/brevity.

In [41]:
#(Write code here)

# Rounding all the list values 
op=[]
for item in kl:
  newlist = round(item,2)
  op.append(newlist)

In [42]:
op

[0,
 0,
 0,
 0,
 7.65,
 7.65,
 16.13,
 8.55,
 6.23,
 1.2,
 1.0,
 0.83,
 1.05,
 3.37,
 3.23,
 3.14,
 3.11,
 3.14,
 5.99,
 2.34,
 2.25,
 2.26,
 2.12,
 -21.68,
 0]

## Step 16 - Add the list of the percentages to the dataframe as a new column ("PCT_CHANGE")

Not as hard as you may think. If you get stuck, you think too hard. Google it and you will find the answer.

In [43]:
#(Write code here)
d_um['PCT_CHANGE'] = op

In [44]:
# Sorting Values the particular Year and Pct_Change column for reference
d_um.sort_values(by = ['YEAR', 'PCT_CHANGE'], ascending=True)

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,YEAR,PCT_CHANGE
2151,163268,University of Maryland-Baltimore County,MD,2.0,NaN,0.0,1996,0.00
2049,163268,University of Maryland-Baltimore County,MD,2.0,NaN,0.0,1997,0.00
1982,163268,University of Maryland-Baltimore County,MD,2.0,NaN,0.0,1998,0.00
1955,163268,University of Maryland-Baltimore County,MD,2.0,NaN,0.0,1999,0.00
1926,163268,University of Maryland-Baltimore County,MD,2.0,NaN,5490.0,2000,7.65
1915,163268,University of Maryland-Baltimore County,MD,2.0,0.6551,5910.0,2001,7.65
1893,163268,University of Maryland-Baltimore County,MD,2.0,0.6327,6362.0,2002,16.13
1873,163268,University of Maryland-Baltimore County,MD,2.0,0.5757,7388.0,2003,8.55
1830,163268,University of Maryland-Baltimore County,MD,2.0,0.7014,8020.0,2004,6.23
1819,163268,University of Maryland-Baltimore County,MD,2.0,0.7143,8520.0,2005,1.20
1799,163268,University of Maryland-Baltimore County,MD,2.0,0.7153,8622.0,2006,1.00
1779,163268,University of Maryland-Baltimore County,MD,2.0,0.6895,8708.0,2007,0.83
1767,163268,University of Maryland-Baltimore County,MD,2.0,0.7174,8780.0,2008,1.05
1745,163268,University of Maryland-Baltimore County,MD,2.0,0.6890,8872.0,2009,3.37
1710,163268,University of Maryland-Baltimore County,MD,2.0,0.6589,9171.0,2010,3.23
1694,163268,University of Maryland-Baltimore County,MD,2.0,0.6081,9467.0,2011,3.14
1660,163268,University of Maryland-Baltimore County,MD,2.0,0.6035,9764.0,2012,3.11
1629,163268,University of Maryland-Baltimore County,MD,2.0,0.6315,10068.0,2013,3.14
1610,163268,University of Maryland-Baltimore County,MD,2.0,0.5961,10384.0,2014,5.99
1555,163268,University of Maryland-Baltimore County,MD,2.0,0.5942,11006.0,2015,2.34
1510,163268,University of Maryland-Baltimore County,MD,2.0,0.5683,11264.0,2016,2.25
1478,163268,University of Maryland-Baltimore County,MD,2.0,0.6021,11518.0,2017,2.26
1415,163268,University of Maryland-Baltimore County,MD,2.0,0.5794,11778.0,2018,2.12
1391,163268,University of Maryland-Baltimore County,MD,2.0,0.6103,12028.0,2019,-21.68
1375,163268,University of Maryland-Baltimore County,MD,2.0,0.6948,9420.0,2020,0.00

## Step 17 - Finaly, we can make the plot tuition growth rate year over year - bar first, then line chart

In [86]:
# (write code here)



fig = px.bar(d_um, x = 'YEAR', y = 'PCT_CHANGE', color='YEAR')
fig.update_layout(title="UMBC tuition growth rate year over year", hovermode="x")
fig.show()

In [85]:
fig = px.line(d_um, x = 'YEAR', y = 'PCT_CHANGE')
fig.update_layout(title="UMBC tuition growth rate year over year", hovermode="x")
fig.show()

## Step 18 - Define Growth Rate Function

Since we want to do the same calculation for JHU. Instead of doing it piecemeal as we did for UMBC. Let's create a function which can be reused for any college. This function takes a list of tuitions and return a list of percentage changes year over year. This function can be used later.

In [47]:
#(Write code here)

# Creating Function for Calculatign Growth

def calPercentageChange(fees):
  j=0
  new_List=[]
  for i in range(0,len(fees)):
    j=i+1
    if fees[i]==0:
      pc=0 # Conditional statement to avoid mathematical error (When any value is divided by 0, it won't work)
      new_List.append(pc)
    else: 
      if j<len(fees): 
        pc = ((fees[j] - fees[i])/fees[i]) *100 # applying % change formula
        new_List.append(pc)
      else:
        pc= 0
        new_List.append(pc)  
  return new_List

calPercentageChange(list_c)

[0,
 0,
 0,
 0,
 7.650273224043716,
 7.648054145516074,
 16.12700408676517,
 8.554412560909583,
 6.234413965087282,
 1.1971830985915493,
 0.9974483878450475,
 0.8268259072117593,
 1.0478359908883828,
 3.370153291253381,
 3.227565151019518,
 3.1372134783986483,
 3.11347808275297,
 3.1386571315057608,
 5.989984591679507,
 2.344175904052335,
 2.254971590909091,
 2.2573363431151243,
 2.122601460349805,
 -21.68274027269704,
 0]

In [48]:
# Rounding Values Again
lm=[]
for item in calPercentageChange(list_c):
  newlist_1 = round(item,2)
  lm.append(newlist_1)

In [49]:
lm

[0,
 0,
 0,
 0,
 7.65,
 7.65,
 16.13,
 8.55,
 6.23,
 1.2,
 1.0,
 0.83,
 1.05,
 3.37,
 3.23,
 3.14,
 3.11,
 3.14,
 5.99,
 2.34,
 2.25,
 2.26,
 2.12,
 -21.68,
 0]

## Step 19 - Get JHU Data

The dataframe contains many years of data of all U.S. colleges. Let's just look at JHU. Filter/query the dataframe to retrieve only rows that belong to JHU. Save the JHU data to a new data frame using a new variable so that the old big data frame is still available for later use.

In [50]:
d_jhu = d_w[d_w['INSTNM'] == 'Johns Hopkins University']
d_jhu

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,YEAR
1792,162928,Johns Hopkins University,MD,2.0,0.2792,33900.0,2006
1738,162928,Johns Hopkins University,MD,2.0,0.2782,39150.0,2009
1865,162928,Johns Hopkins University,MD,2.0,0.3060,28730.0,2003
1973,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1998
1653,162928,Johns Hopkins University,MD,2.0,0.1843,43390.0,2012
1386,162928,Johns Hopkins University,MD,2.0,0.1117,55350.0,2019
1687,162928,Johns Hopkins University,MD,2.0,0.1940,42280.0,2011
1603,162928,Johns Hopkins University,MD,2.0,0.1608,47060.0,2014
1917,162928,Johns Hopkins University,MD,2.0,NaN,24930.0,2000
1772,162928,Johns Hopkins University,MD,2.0,0.2571,35900.0,2007
1503,162928,Johns Hopkins University,MD,2.0,0.1284,50410.0,2016
1410,162928,Johns Hopkins University,MD,2.0,0.1148,53740.0,2018
1760,162928,Johns Hopkins University,MD,2.0,0.2609,37700.0,2008
1884,162928,Johns Hopkins University,MD,2.0,0.3506,27390.0,2002
1823,162928,Johns Hopkins University,MD,2.0,0.3071,30140.0,2004
1703,162928,Johns Hopkins University,MD,2.0,0.2225,40680.0,2010
1622,162928,Johns Hopkins University,MD,2.0,0.1813,45470.0,2013
1812,162928,Johns Hopkins University,MD,2.0,0.3509,31620.0,2005
1946,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1999
1548,162928,Johns Hopkins University,MD,2.0,0.1412,48710.0,2015
2139,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1996
1473,162928,Johns Hopkins University,MD,2.0,0.1254,52170.0,2017
2039,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1997
1370,162928,Johns Hopkins University,MD,2.0,0.1106,54160.0,2020
1906,162928,Johns Hopkins University,MD,2.0,0.3431,26210.0,2001

## Step 20 - Plot JHU's in-state tuition overtime

Let's plot bar and then line chart.

In [84]:
# <14> 
# Plot JHU's in-state tuition overtime from 1996 to 2019. 
# Let's plot bar and line chart together

#(Write code here)

fig = px.bar(d_jhu, x = 'YEAR', y = 'TUITIONFEE_IN', color='TUITIONFEE_IN')
fig.update_layout(title="JHU's in-state tuition over time", hovermode="x")
fig.show()

In [83]:

# Creating Line PLot


fig = px.line(d_jhu, x = 'YEAR', y = 'TUITIONFEE_IN')
fig.update_layout(title="JHU's in-state tuition over time", hovermode="x")
fig.show()

In [53]:
# Sorting columns and filling the missing values

d_jhu = d_jhu.sort_values('YEAR', ascending=True)
d_jhu['TUITIONFEE_IN'] = d_jhu['TUITIONFEE_IN'].fillna(0)
d_jhu

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,YEAR
2139,162928,Johns Hopkins University,MD,2.0,NaN,0.0,1996
2039,162928,Johns Hopkins University,MD,2.0,NaN,0.0,1997
1973,162928,Johns Hopkins University,MD,2.0,NaN,0.0,1998
1946,162928,Johns Hopkins University,MD,2.0,NaN,0.0,1999
1917,162928,Johns Hopkins University,MD,2.0,NaN,24930.0,2000
1906,162928,Johns Hopkins University,MD,2.0,0.3431,26210.0,2001
1884,162928,Johns Hopkins University,MD,2.0,0.3506,27390.0,2002
1865,162928,Johns Hopkins University,MD,2.0,0.3060,28730.0,2003
1823,162928,Johns Hopkins University,MD,2.0,0.3071,30140.0,2004
1812,162928,Johns Hopkins University,MD,2.0,0.3509,31620.0,2005
1792,162928,Johns Hopkins University,MD,2.0,0.2792,33900.0,2006
1772,162928,Johns Hopkins University,MD,2.0,0.2571,35900.0,2007
1760,162928,Johns Hopkins University,MD,2.0,0.2609,37700.0,2008
1738,162928,Johns Hopkins University,MD,2.0,0.2782,39150.0,2009
1703,162928,Johns Hopkins University,MD,2.0,0.2225,40680.0,2010
1687,162928,Johns Hopkins University,MD,2.0,0.1940,42280.0,2011
1653,162928,Johns Hopkins University,MD,2.0,0.1843,43390.0,2012
1622,162928,Johns Hopkins University,MD,2.0,0.1813,45470.0,2013
1603,162928,Johns Hopkins University,MD,2.0,0.1608,47060.0,2014
1548,162928,Johns Hopkins University,MD,2.0,0.1412,48710.0,2015
1503,162928,Johns Hopkins University,MD,2.0,0.1284,50410.0,2016
1473,162928,Johns Hopkins University,MD,2.0,0.1254,52170.0,2017
1410,162928,Johns Hopkins University,MD,2.0,0.1148,53740.0,2018
1386,162928,Johns Hopkins University,MD,2.0,0.1117,55350.0,2019
1370,162928,Johns Hopkins University,MD,2.0,0.1106,54160.0,2020

In [54]:
list_jhu = d_jhu['TUITIONFEE_IN'].to_list()
list_jhu

[0.0,
 0.0,
 0.0,
 0.0,
 24930.0,
 26210.0,
 27390.0,
 28730.0,
 30140.0,
 31620.0,
 33900.0,
 35900.0,
 37700.0,
 39150.0,
 40680.0,
 42280.0,
 43390.0,
 45470.0,
 47060.0,
 48710.0,
 50410.0,
 52170.0,
 53740.0,
 55350.0,
 54160.0]

## Step 21 - Calculate Tuition Growth Rate using the Function defined earlier

In [55]:
# Write code here
def calPercentageChange(fees):
  j=0
  new_List_1=[]
  for i in range(0,len(fees)):
    j=i+1
    if fees[i]==0:
      pc=0
      new_List_1.append(pc)
    else: 
      if j<len(fees): 
        pc = ((fees[j] - fees[i])/fees[i]) *100
        new_List_1.append(pc)
      else:
        pc= 0
        new_List_1.append(pc)  
  return new_List_1

calPercentageChange(list_jhu)

[0,
 0,
 0,
 0,
 5.134376253509827,
 4.502098435711561,
 4.8922964585615185,
 4.907761921336582,
 4.91041804910418,
 7.2106261859582546,
 5.899705014749262,
 5.013927576601671,
 3.8461538461538463,
 3.9080459770114944,
 3.933136676499508,
 2.6253547776726585,
 4.793731274487209,
 3.496811084231361,
 3.5061623459413513,
 3.4900431122972697,
 3.4913707597698873,
 3.0093923710944988,
 2.995906215109788,
 -2.149954832881662,
 0]

In [56]:
iub=[]
for item in calPercentageChange(list_jhu):
  newlist = round(item,2)
  iub.append(newlist)

In [57]:
iub

[0,
 0,
 0,
 0,
 5.13,
 4.5,
 4.89,
 4.91,
 4.91,
 7.21,
 5.9,
 5.01,
 3.85,
 3.91,
 3.93,
 2.63,
 4.79,
 3.5,
 3.51,
 3.49,
 3.49,
 3.01,
 3.0,
 -2.15,
 0]

## Step 22 - Add the list of percentage changes to the dataframe as a new column ("PCT_CHANGE")

In [58]:
#(Write code here)
d_jhu['PCT_CHANGE'] = iub

In [59]:
d_jhu['PCT_CHANGE']

2139    0.00
2039    0.00
1973    0.00
1946    0.00
1917    5.13
1906    4.50
1884    4.89
1865    4.91
1823    4.91
1812    7.21
1792    5.90
1772    5.01
1760    3.85
1738    3.91
1703    3.93
1687    2.63
1653    4.79
1622    3.50
1603    3.51
1548    3.49
1503    3.49
1473    3.01
1410    3.00
1386   -2.15
1370    0.00
Name: PCT_CHANGE, dtype: float64

## Step 23 - Plot the JHU percentage changes tuitions over time

Bar plot first, then line plot.

In [82]:
#(Write code here)

# Bar Plot

fig = px.bar(d_jhu, x = 'YEAR', y = 'PCT_CHANGE')
fig.update_layout(title="JHU percentage change over time", hovermode="x")
fig.show()

In [81]:
# line PLot
fig = px.line(d_jhu, x = 'YEAR', y = 'PCT_CHANGE')
fig.update_layout(title="JHU percentage change over time", hovermode="x")
fig.show()

## Step 24 - Compare UMBC and JHU 

In order to plot both UMBC and JHU tuition change over time in the same plot, we need to combine the two datasets using the common key of YEAR. 

First make a umbc2 dataframe with only two columns needed. We don't need other columns. Also change the column name from "PCT_CHANGE" to "UMBC_PCT" in preparation for the merge. This is because both umbc and jhu dataframe have the same column name "PCT_CHANGE", we rename them to there is no collision during the merge. BTW, Pandas handles collision gracefully, Feel free to try it without changing the column names.

In [62]:
#(Write code here)
d_umbc2 = pd.DataFrame(d_um)
d_umbc2 = d_umbc2[['YEAR', 'PCT_CHANGE']]
d_umbc2.rename(columns={"PCT_CHANGE":"UMBC_PCT"})
d_umbc2.set_index('YEAR')

      PCT_CHANGE
YEAR
1996        0.00
1997        0.00
1998        0.00
1999        0.00
2000        7.65
2001        7.65
2002       16.13
2003        8.55
2004        6.23
2005        1.20
2006        1.00
2007        0.83
2008        1.05
2009        3.37
2010        3.23
2011        3.14
2012        3.11
2013        3.14
2014        5.99
2015        2.34
2016        2.25
2017        2.26
2018        2.12
2019      -21.68
2020        0.00

## Step 25 

Then make a jhu2 dataframe with only two columns needed. WE don't need other columns. Also change the column name from "PCT_CHANGE" to "JHU_PCT"  in preparation for the merge

In [63]:
#(Write code here)

d_jhu2 = pd.DataFrame(d_jhu)
d_jhu2 = d_jhu2[['YEAR', 'PCT_CHANGE']]
d_jhu2.rename(columns={"PCT_CHANGE":"JHU_PCT"})
d_jhu2.set_index('YEAR')

      PCT_CHANGE
YEAR
1996        0.00
1997        0.00
1998        0.00
1999        0.00
2000        5.13
2001        4.50
2002        4.89
2003        4.91
2004        4.91
2005        7.21
2006        5.90
2007        5.01
2008        3.85
2009        3.91
2010        3.93
2011        2.63
2012        4.79
2013        3.50
2014        3.51
2015        3.49
2016        3.49
2017        3.01
2018        3.00
2019       -2.15
2020        0.00

## Step 26 - Merger the two data frames and display the new dataframe

In [64]:
#(Write code here)

d_mg = pd.merge(d_umbc2, d_jhu2, on='YEAR')
d_mg

    YEAR  PCT_CHANGE_x  PCT_CHANGE_y
0   1996          0.00          0.00
1   1997          0.00          0.00
2   1998          0.00          0.00
3   1999          0.00          0.00
4   2000          7.65          5.13
5   2001          7.65          4.50
6   2002         16.13          4.89
7   2003          8.55          4.91
8   2004          6.23          4.91
9   2005          1.20          7.21
10  2006          1.00          5.90
11  2007          0.83          5.01
12  2008          1.05          3.85
13  2009          3.37          3.91
14  2010          3.23          3.93
15  2011          3.14          2.63
16  2012          3.11          4.79
17  2013          3.14          3.50
18  2014          5.99          3.51
19  2015          2.34          3.49
20  2016          2.25          3.49
21  2017          2.26          3.01
22  2018          2.12          3.00
23  2019        -21.68         -2.15
24  2020          0.00          0.00

## Step 27 - Plot UMBC and JHU separately on the same line plot

In [65]:
#(Write code here)

# Importing Plotly Libraries

import plotly.express as px
import plotly.graph_objects as go

In [66]:
# Using PLotly in order to Hover the comparision between two separate DataFrame

fig = go.Figure()

fig.add_trace(
    go.Scatter(x=d_mg.YEAR, y=d_mg.PCT_CHANGE_x, name="umbc")
)

fig.add_trace(
    go.Scatter(x=d_mg.YEAR, y=d_mg.PCT_CHANGE_y, name="jhu")
)

fig.update_layout(title="UMBC and JHU percentage change over time", hovermode="x")
fig.update_xaxes(title="Year")
fig.update_yaxes(title="UMBC and JHU percentage change")

## Step 28 - Document your observation of the comparison plots using the following Markdown cell

#### As shown in the chart above, UMBC and JHU started out on the same level, UMBC's employemnt change went significantly up around 2002 but then coming to the present time they are somewhat similar but with a negative 21% change of UMBC in 2019.